// Generated by CoffeeScript 1.4.0
(function() {
  var RequestHandler, Router, journey;

  journey = require('journey');

  RequestHandler = require('./RequestHandler').RequestHandler;

  Router = (function() {

    function Router() {}

    Router.init = function() {
      var _this = this;
      this.jRouter || (this.jRouter = new journey.Router);
      return this.jRouter.map(function() {
        var handle, method, _i, _len, _ref, _results;
        _ref = RequestHandler.getHandlers();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          handle = _ref[_i];
          method = handle.method || "get";
          if (typeof console !== "undefined" && console !== null) {
            console.log(handle);
          }
          _results.push(_this.jRouter[method](handle.category).bind(handle.route));
        }
        return _results;
      });
    };

    Router.handle = function(request, body, callback) {
      return this.jRouter.handle(request, body, callback);
    };

    return Router;

  })();

  exports.Router = Router;

}).call(this);
