// Generated by CoffeeScript 1.4.0
(function() {
  var Router, Server, http;

  http = require('http');

  Router = require('./Router').Router;

  Server = {
    start: function() {
      Router.init();
      return http.createServer(function(request, response) {
        var body,
          _this = this;
        body = "";
        request.addListener('data', function(chunk) {
          return body += chunk;
        });
        return request.addListener('end', function() {
          return Router.handle(request, body, function(result) {
            response.writeHead(result.status, result.headers);
            return response.end(result.body);
          });
        });
      }).listen(8080);
    }
  };

  exports.Server = Server;

}).call(this);
