// Generated by CoffeeScript 1.4.0
(function() {
  var $, CryptoJS, addrList, doEncrypt, encodeToUTF8, encryptAndPost, getCheck, hmacKey, options, pgpId, pgpKey, postData, postWrapper, ramdomAddr, ramdomDate, ramdomID, ramdomMail, ramdomRegister;

  CryptoJS = require("./hmac-sha256.js").CryptoJS;

  doEncrypt = require("./PGencode.js").doEncrypt;

  pgpKey = require("./keys.js").pgpKey;

  hmacKey = require("./keys.js").hmacKey;

  pgpId = require("./keys.js").pgpId;

  addrList = require("./addrList.js").addrList;

  $ = require("jquery");

  encodeToUTF8 = function(strUni) {
    var strUtf;
    strUtf = strUni.replace(/[\u0080-\u07ff]/g, function(c) {
      var cc;
      cc = c.charCodeAt(0);
      return String.fromCharCode(0xc0 | cc >> 6, 0x80 | cc & 0x3f);
    });
    return strUtf = strUtf.replace(/[\u0800-\uffff]/g, function(c) {
      var cc;
      cc = c.charCodeAt(0);
      return String.fromCharCode(0xe0 | cc >> 12, 0x80 | cc >> 6 & 0x3F, 0x80 | cc & 0x3f);
    });
  };

  ramdomDate = function() {
    var day, month, year;
    year = Math.round(Math.random() * 20) + 1 + 1970;
    month = "" + (Math.round(Math.random() * 11) + 1);
    if (month.length === 1) {
      month = "0" + month;
    }
    day = "" + (Math.round(Math.random() * 28) + 1);
    if (day.length === 1) {
      day = "0" + day;
    }
    return "" + year + month + day;
  };

  ramdomAddr = function() {
    var addr, line;
    line = Math.round(Math.random() * (addrList.length - 1));
    addr = addrList[line];
    return "" + addr;
  };

  ramdomRegister = function() {
    var num;
    num = Math.round(Math.random() * 1000);
    return "" + num;
  };

  getCheck = function(key17) {
    var ai, c, checkList, index, sum, v, _i, _len;
    if (key17.length !== 17) {
      return;
    }
    ai = [7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2];
    checkList = [1, 0, "X", 9, 8, 7, 6, 5, 4, 3, 2];
    sum = 0;
    for (index = _i = 0, _len = ai.length; _i < _len; index = ++_i) {
      v = ai[index];
      sum += ai[index] * (+key17[index]);
    }
    c = sum % 11;
    return "" + checkList[c];
  };

  ramdomID = function() {
    var c, id, id17;
    id17 = "" + (ramdomAddr()) + (ramdomDate()) + (ramdomRegister());
    c = getCheck(id17);
    id = "" + id17 + c;
    console.log("id number is " + id);
    return id;
  };

  ramdomMail = function() {
    var num;
    num = Math.round(Math.random() * 1000);
    return "superway.pan." + num + "@gmail.com";
  };

  encryptAndPost = function(keyValue, iShoppingCartObject, succCount, failCount) {
    var aPayLoad, anEncryptedKey, anEncryptedPayload;
    anEncryptedKey = CryptoJS.HmacSHA256(keyValue + iShoppingCartObject.productName, hmacKey);
    if (pgpKey !== null && pgpId !== null) {
      aPayLoad = "" + iShoppingCartObject.governmentID + ",zh_CN," + iShoppingCartObject.storeNumber + "," + iShoppingCartObject.sku + "," + iShoppingCartObject.quantity + "," + iShoppingCartObject.firstName + "," + iShoppingCartObject.lastName + "," + iShoppingCartObject.emailAddress + "," + iShoppingCartObject.phoneNumber + "," + iShoppingCartObject.productName + "," + iShoppingCartObject.planType;
      console.log("aPayLoad=" + aPayLoad);
      aPayLoad = encodeToUTF8(aPayLoad);
      anEncryptedPayload = doEncrypt(pgpId, 0, pgpKey, aPayLoad);
      return $.ajax({
        type: "POST",
        data: 'key=#{anEncryptedKey}&payload=#{anEncryptedPayload}',
        url: "https://reserve-cn.appleonline.net/reservation/create",
        success: function(xhr) {
          console.log("Post success");
          return succCount++;
        },
        error: function(xhr) {
          console.log("Error occurred");
          return failCount++;
        }
      });
    }
  };

  postData = function(succCount, failCount, options) {
    var iShoppingCartObject;
    if (!options) {
      options = {};
    }
    if (!options.store) {
      options.store = "R359";
    }
    if (!options.sku) {
      options.sku = "MD531CH/A";
    }
    if (!options.key) {
      options.key = ramdomID();
    }
    if (!options.mail) {
      options.mail = ramdomMail();
    }
    iShoppingCartObject = {
      "emailAddress": options.mail,
      "firstName": "Eason",
      "lastName": "eason",
      "governmentID": options.key,
      "phoneNumber": void 0,
      "planType": void 0,
      "productName": "iPad",
      "quantity": "2",
      "sku": options.sku,
      "storeNumber": options.store
    };
    return encryptAndPost(options.key, iShoppingCartObject, succCount, failCount);
  };

  postWrapper = function(options) {
    var count, failCount, post, succCount, timerID;
    count = 0;
    succCount = 0;
    failCount = 0;
    post = function() {
      postData(succCount, failCount, options);
      if (count++ > 50000) {
        console.log("Done sent 50000");
        return clearInterval(timerID);
      }
    };
    return timerID = setInterval(post, 1000);
  };

  postWrapper();

  options = {
    "key": "360203198111073519",
    "mail": "superway_build@yahoo.com.cn",
    "sku": "MD528CH/A",
    "storeNumber": "R389"
  };

  postWrapper(options);

  /*
  options1 = 
      {
          "key": "360203198111073519",
          "mail": "superway_build@yahoo.com.cn",
          "sku": "MD528CH/A",    #  MD528CH/A black MD531CH/A white
          "storeNumber": "R359"  #R359 nanjin road/R389 pudong
      }
  postWrapper(options1)
  
  options2 = 
      {
          "key": "360203198111073519",
          "mail": "superway_build@yahoo.com.cn",
          "sku": "MD531CH/A",    #  MD528CH/A black MD531CH/A white
          "storeNumber": "R389"  #R359 nanjin road/R389 pudong
      }
  postWrapper(options2)
  
  
  options3 = 
      {
          "key": "360203198111073519",
          "mail": "superway_build@hotmail.com",
          "sku": "MD528CH/A",    #  MD528CH/A black MD531CH/A white
          "storeNumber": "R359"  #R359 nanjin road/R389 pudong
      }
  postWrapper(options3)
  
  options4 = 
      {
          "key": "360203198111073519",
          "mail": "superway_build@hotmail.com",
          "sku": "MD531CH/A",    #  MD528CH/A black MD531CH/A white
          "storeNumber": "R389"  #R359 nanjin road/R389 pudong
      }
  postWrapper(options4)
  */


}).call(this);
