// Generated by CoffeeScript 1.4.0
(function() {
  var $, CryptoJS, doEncrypt, encodeToUTF8, encryptAndPost, hmacKey, pgpId, pgpKey, postData, ramdomAddr, ramdomDate, ramdomID, ramdomRegister, timerCount, timerID;

  CryptoJS = require("./hmac-sha256.js").CryptoJS;

  doEncrypt = require("./PGencode.js").doEncrypt;

  pgpKey = require("./keys.js").pgpKey;

  hmacKey = require("./keys.js").hmacKey;

  pgpId = require("./keys.js").pgpId;

  $ = require("jquery");

  encodeToUTF8 = function(strUni) {
    var strUtf;
    strUtf = strUni.replace(/[\u0080-\u07ff]/g, function(c) {
      var cc;
      cc = c.charCodeAt(0);
      return String.fromCharCode(0xc0 | cc >> 6, 0x80 | cc & 0x3f);
    });
    return strUtf = strUtf.replace(/[\u0800-\uffff]/g, function(c) {
      var cc;
      cc = c.charCodeAt(0);
      return String.fromCharCode(0xe0 | cc >> 12, 0x80 | cc >> 6 & 0x3F, 0x80 | cc & 0x3f);
    });
  };

  encryptAndPost = function(keyValue, iShoppingCartObject) {
    var aPayLoad, anEncryptedKey, anEncryptedPayload;
    anEncryptedKey = CryptoJS.HmacSHA256(keyValue + iShoppingCartObject.productName, hmacKey);
    if (pgpKey !== null && pgpId !== null) {
      aPayLoad = "" + iShoppingCartObject.governmentID + ",zh_CN," + iShoppingCartObject.storeNumber + "            ," + iShoppingCartObject.sku + "," + iShoppingCartObject.quantity + "            ," + iShoppingCartObject.firstName + "," + iShoppingCartObject.lastName + "            ," + iShoppingCartObject.emailAddress + "," + iShoppingCartObject.phoneNumber + "            ," + iShoppingCartObject.productName + "," + iShoppingCartObject.planType;
      aPayLoad = encodeToUTF8(aPayLoad);
      anEncryptedPayload = doEncrypt(pgpId, 0, pgpKey, aPayLoad);
      console.log(anEncryptedKey);
      console.log(anEncryptedPayload);
      return $.ajax({
        type: "POST",
        data: 'key=#{anEncryptedKey}&payload=#{anEncryptedPayload}',
        url: "https://reserve-cn.appleonline.net/reservation/create",
        success: function(xhr) {
          return console.log("post success");
        },
        error: function(xhr) {
          return console.log("Error occurred while communicating with the server");
        }
      });
    }
  };

  timerCount = 0;

  ramdomDate = function() {
    var day, month, year;
    year = Math.round(Math.random() * 20) + 1 + 1970;
    month = "" + (Math.round(Math.random() * 11) + 1);
    if (month.length === 1) {
      month = "0" + month;
    }
    day = "" + (Math.round(Math.random() * 28) + 1);
    if (day.length === 1) {
      day = "0" + day;
    }
    console.log("born date is " + year + month + day);
    return "" + year + month + day;
  };

  ramdomAddr = function() {
    var addr, end, start;
    start = 110000;
    end = 659004;
    addr = start + Math.round(Math.random() * 10000);
    console.log("addr is " + addr);
    return "" + addr;
  };

  ramdomRegister = function() {
    var check, num;
    num = Math.round(Math.random() * 1000);
    check = Math.round(Math.random() * 10);
    console.log("register is " + num + check);
    return "" + num + check;
  };

  ramdomID = function() {
    var id;
    id = "" + (ramdomAddr()) + (ramdomDate()) + (ramdomRegister());
    console.log("id number is " + id);
    return id;
  };

  postData = function() {
    var iShoppingCartObject, keyvalue;
    keyvalue = ramdomID();
    iShoppingCartObject = {
      "emailAddress": "superway.pan@gmail.com",
      "firstName": "Li",
      "lastName": "Sheng",
      "governmentID": keyvalue,
      "phoneNumber": "phoneNumberundefined",
      "planType": void 0,
      "productName": "iPad",
      "quantity": "2",
      "sku": "MD531CH/A",
      "storeNumber": "R359"
    };
    encryptAndPost(keyvalue, iShoppingCartObject);
    timerCount++;
    if (timerCount > 2) {
      return clearInterval(timerID);
    }
  };

  timerID = setInterval(postData, 10000);

}).call(this);
